Update probely-gha-cli.yml

diff --git a/.github/workflows/probely-gha-cli.yml b/.github/workflows/probely-gha-cli.yml
--- a/.github/workflows/probely-gha-cli.yml
+++ b/.github/workflows/probely-gha-cli.yml
@@ -29,7 +29,7 @@ jobs:
       # Step 3: Wait for scan to end
       - name: Wait for scan to end
         run: |
-          probely scans get $SCAN_ID -o JSON
+          probely scans get $SCAN_ID
           # Wait until scan ends
           while true; do
             echo "-----------------------------------"
@@ -43,4 +43,17 @@ jobs:
             fi
             sleep 30;
           done
+
+      # Step 4: Optional logic - abort the pipeline if there are any HIGH risk vulnerabilities.
+      - name: Check for High risk vulnerabilities
+        run: |
+          # Wait until scan ends
+          HIGH_VULNS=$(probely scans get $SCAN_ID -o JSON | jq -r '.[0].highs')
+          echo "HIGH risk vulnerabilities ${HIGH_VULNS}"
+          if [[ "$HIGH_VULNS" -gt 0 ]]; then
+            echo "Scan has High risk vulnerabilities... aborting"
+            exit 1
+          else
+            echo "Scan doesn't have High risk vulnerabilities"
+          fi
           
